// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH4FYSKTOXPrvNLWK2oRUvtU2y0cw-eYQ',
    appId: '1:1018312039129:web:1d2c8a94efe4aff9133cc8',
    messagingSenderId: '1018312039129',
    projectId: 'artfolioapp-faaf9',
    authDomain: 'artfolioapp-faaf9.firebaseapp.com',
    storageBucket: 'artfolioapp-faaf9.appspot.com',
    measurementId: 'G-LQYFQP5TKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6PcL7d9eaHthdMmADIUFkEuRYPc6Vw1s',
    appId: '1:1018312039129:android:e20a1092ddabab3d133cc8',
    messagingSenderId: '1018312039129',
    projectId: 'artfolioapp-faaf9',
    storageBucket: 'artfolioapp-faaf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQiZNfr9RU5cVn1ixHXq2tXEEmXazULo',
    appId: '1:1018312039129:ios:2eae88ac0be72bf8133cc8',
    messagingSenderId: '1018312039129',
    projectId: 'artfolioapp-faaf9',
    storageBucket: 'artfolioapp-faaf9.appspot.com',
    iosBundleId: 'com.example.artfolioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaQiZNfr9RU5cVn1ixHXq2tXEEmXazULo',
    appId: '1:1018312039129:ios:2eae88ac0be72bf8133cc8',
    messagingSenderId: '1018312039129',
    projectId: 'artfolioapp-faaf9',
    storageBucket: 'artfolioapp-faaf9.appspot.com',
    iosBundleId: 'com.example.artfolioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH4FYSKTOXPrvNLWK2oRUvtU2y0cw-eYQ',
    appId: '1:1018312039129:web:2fd67b0c8f3d49a9133cc8',
    messagingSenderId: '1018312039129',
    projectId: 'artfolioapp-faaf9',
    authDomain: 'artfolioapp-faaf9.firebaseapp.com',
    storageBucket: 'artfolioapp-faaf9.appspot.com',
    measurementId: 'G-Y9B3VXEZLH',
  );
}
